TAG: "lithofacies_prediction_25.0_pat"
CUDNN_BENCHMARK: True
SEED: 654326212
DEVICE: "cuda"
GPUS: [ 6, 7, 8, 9 ]

PRETRAIN:
  LOAD: False
  TAG: "lithofacies_prediction_25.0_pat"
  LOAD_EPOCH: 32
  LOAD_OPTIMIZER: True

DATASET:
  DATA_POOL: "southsea"
  VOLUME_TAG: "3dn_tbcut"
  FACIES_TAG: "3dn_facies_unc"
  TRAIN_BATCH_SIZE: 40
  VALID_BATCH_SIZE: 40
  TRAIN_IDX: [ 0, 2000 ]
  VALID_IDX: [ 2000, 2667 ]
  TRAIN_CROP_SIZE: [ 256, 256 ]
  VALID_CROP_SIZE: [ 256, 256 ]
  VDT: 12.5
  TDT: 25.0
  TRAIN_NUM_DATA: 16000
  VALID_NUM_DATA: 4000
  FLIP: True
  SCALE: True
  NOISE: 0.01
  NUM_WORKER: 1

MODEL:
  A_CHANNELS: 1
  B_CHANNELS: 6
  INFO_CHANNELS: 2  # instantaneous phase + instantaneous frequency
  GEN_CHANNELS: 32
  GEN_NORM: True
  GEN_ATTN: True

TRAIN:
  BEGIN_EPOCH: 0
  END_EPOCH: 50
  CHECK_EPOCH: 1
  LR: 0.00001
  LR_EXP: 0.999
  BETA1: 0.9
  BETA2: 0.999

EVAL:
  BATCH_SIZE_FID: 28
  BEGIN_EPOCH: 300
  END_EPOCH: 500
  STEP_EPOCH: 10
